use_frameworks!

platform :ios, '9.0'

target 'ZHAFNNetwork_Example' do
  pod 'ZHAFNNetwork', :path => '../'

  target 'ZHAFNNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
