use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'ZHAFNNetwork_Example' do
  pod 'ZHAFNNetwork', :path => '../'
  
  pod 'AFNetworking'
  pod 'YYCache'
  
end
